# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI (Lint & pytest)

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: Gr1N/setup-poetry@v8 #install poetry
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements with poetry
      run: poetry install
    - name: Lint with Ruff
      run: poetry run ruff check --output-format=github .
    - name: Test with pytest
      run: poetry run pytest
